version: '3.7'

services:
  postgres:
    image: postgres
    ports:
    - "5432:5432"
  django:
    restart: always
    volumes:
      - .:/subt_root
    depends_on:
      - postgres
    build: ./project
    ports:
      - 8000:8000
    links:
      - postgres:postgres
    working_dir: /subt_root/project
    command: python entry_point.py

volumes:
  postgres_data:
  redisdata:
